### ISSUE TITLE
Is there a way to have `Data::Dump::Color` output to `STDERR` instead of `STDOUT`?

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#11]
I'm printing out some JSON and sprinkling `Data::Dump::Color` in my code to test things. Everytime I do this it breaks the JSON parsing because of the embedded debug output.

If there was a way to have `Data::Dump::Color` output to `STDERR` instead then the JSON would parse correctly. Is there a way to do that currently? Or would that be a complicated addition?

**Comment by perlancar** [comment]
Yes, there is. Like [Data::Dump](https://metacpan.org/pod/Data::Dump), if you call `dump()` in void context, it prints to STDERR.
