### ISSUE TITLE
I use Data::Dump::Color every day and I love it

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#12]
Just wanted to report that I'm still using `Data::Dump::Color` every day and it works great. I did some benchmarking and I thought it was worth reporting that `Data::Dump::Color` loads faster than `Data::Dumper`.

I wrote a [simple benchmark](https://www.perturb.org/code/perl-module-startup-time.pl) to measure common modules and their effect on script startup time.

```
Establishing baseline... 42.9 ms

'use strict' adds 0.8 ms to startup time
'use warnings' adds 3.1 ms to startup time
'use v5.16' adds 0.6 ms to startup time
'use Getopt::Long' adds 21.3 ms to startup time
'use Path::Tiny' adds 31.9 ms to startup time
'use JSON::PP' adds 26.0 ms to startup time
'use Data::Dumper' adds 17.2 ms to startup time
'use Data::Dump::Color' adds 16.5 ms to startup time
'use FindBin' adds 20.7 ms to startup time
'use File::Basename' adds 6.5 ms to startup time
'use Time::HiRes' adds 7.7 ms to startup time
'use English' adds 10.6 ms to startup time
'use Term::ANSIColor' adds 12.6 ms to startup time
'use Time::Piece' adds 22.3 ms to startup time
```

**Comment by perlancar** [comment]
Hi Scott, thanks. Data::Dumper (DD) is slower to start probably because it loads Carp and XS modules. Both DD and Data::Dump::Color (DDC) delay loading modules, DDC just do it more. And I do tend to avoid Carp due to its heaviness, and just die() like an old-timer. If one needs stacktrace, he/she can use Devel::Cover.

To benchmark module startup overhead, you can also try my `pmcost` or `bencher-module-startup-overhead`, both available on CPAN. Here's `pmcost` output for DD and DDC:

    % pmcost Data::Dump::Color
    
    # Start stats from Devel::EndStats:
    # Program runtime duration: 5.199ms
    # Total number of required files loaded: 4
    # Total number of required lines loaded: 1503
    # Seq  Lines  Load Time         Module
    #   1    980     5.082ms( 97%)    Data/Dump/Color.pm (loaded by main)
    #   8     99     0.241ms(  4%)    overloading.pm (loaded by overload)
    #   9     52     0.193ms(  3%)    Scalar/Util/LooksLikeNumber.pm (loaded by Data::Dump::Color)
    #   ?    372     0.000ms(  0%)    XSLoader.pm (loaded by ?)
    # End of stats
    
    % pmcost Data::Dumper
    
    # Start stats from Devel::EndStats:
    # Program runtime duration: 7.665ms
    # Total number of required files loaded: 6
    # Total number of required lines loaded: 3606
    # Seq  Lines  Load Time         Module
    #   1   1485     7.518ms( 98%)    Data/Dumper.pm (loaded by main)
    #   6   1072     2.956ms( 38%)    Carp.pm (loaded by Data::Dumper)
    #   3    450     0.987ms( 12%)    constant.pm (loaded by Data::Dumper)
    #   8     99     0.277ms(  3%)    overloading.pm (loaded by Carp)
    #  10    128     0.207ms(  2%)    bytes.pm (loaded by Data::Dumper)
    #   ?    372     0.000ms(  0%)    XSLoader.pm (loaded by ?)
    # End of stats
