### ISSUE TITLE
`Data::Dump::Color` is very slow to load when `Proc::ProcessTable` is installed

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#15]
This is a super weird problem, so I'm hoping maybe you have an idea of where the issue lies. Per my [Reddit post](https://www.reddit.com/r/perl/comments/19dvfdt/i_messed_up_my_perl5_directory_somehow_and_now/) from a couple of days ago loading `Data::Dump::Color` was taking 200ms on my machine instead of the 20ms it normally does. After some [digging with NYTProf](https://scott.web-ster.com/tmp/perl-profile/Proc-ProcessTable-pm-35-line.html#157) I was able to determine the slowdown is in a callback that `File::Find` uses that uses `Proc::ProcessTable`. I am able to recreate this issue on a clean Perl install:

```
bakers@basement(~/github/perl-Data-Dump-Color)
$ time perl -E 'use Data::Dump::Color; dd(9);' 
9

real    0m0.020s
user    0m0.018s
sys     0m0.001s

bakers@basement(~/github/perl-Data-Dump-Color)
$ cpanm Proc::ProcessTable
--> Working on Proc::ProcessTable
Fetching http://www.cpan.org/authors/id/J/JW/JWB/Proc-ProcessTable-0.636.tar.gz ... OK
Configuring Proc-ProcessTable-0.636 ... OK
Building and testing Proc-ProcessTable-0.636 ... OK
Successfully installed Proc-ProcessTable-0.636
1 distribution installed

bakers@basement(~/github/perl-Data-Dump-Color)
$ time perl -E 'use Data::Dump::Color; dd(9);' 
9

real    0m0.221s
user    0m0.100s
sys     0m0.121s
```

Simply having `Proc::ProcessTable` installed seriously slows down loading of `Data::Dump::Color`? Luckily it's an easy fix, as I can simply remove `Proc::ProcessTable` but that seems hacky. Any idea why this would be a slow down? I don't see any calls to either `File::Find` or  `Proc::ProcessTable` in this repo so I'm confused.

**Comment by perlancar** [comment]
Can't reproduce here, also have Proc::ProcessTable installed. Could you trace which module loads Proc::ProcessTable? For example, on my system using [Devel::EndStats](https://metacpan.org/pod/Devel::EndStats]:

    $ pmversion Proc::ProcessTable
    0.636

    $ perl -MDevel::EndStats=time_hires,1,verbose,1 -MData::Dump::Color -E'dd (9)'
    # Start stats from Devel::EndStats:
    # Program runtime duration: 13.270ms
    # Total number of required files loaded: 15
    # Total number of required lines loaded: 8251
    # Seq  Lines  Load Time         Module
    #   ?    681     0.000ms(  0%)    Time/HiRes.pm (loaded by ?)
    #   ?    518     0.000ms(  0%)    Devel/EndStats.pm (loaded by ?)
    #   ?    605     0.000ms(  0%)    Exporter.pm (loaded by ?)
    #   ?    185     0.000ms(  0%)    strict.pm (loaded by ?)
    #   ?    375     0.000ms(  0%)    XSLoader.pm (loaded by ?)
    #  10     52     0.240ms(  1%)    Scalar/Util/LooksLikeNumber.pm (loaded by Data::Dump::Color)
    #  12    112     0.261ms(  1%)    ColorThemeUtil/ANSI.pm (loaded by Data::Dump::Color)
    #   5     84     0.837ms(  6%)    vars.pm (loaded by Data::Dump::Color)
    #   3     43     3.829ms( 28%)    subs.pm (loaded by Data::Dump::Color)
    #   8   1701     1.873ms( 14%)    overload.pm (loaded by Data::Dump::Color)
    #   1   1006    11.916ms( 89%)    Data/Dump/Color.pm (loaded by main)
    #  11   1250     0.827ms(  6%)    feature.pm (loaded by main)
    #   9     99     0.414ms(  3%)    overloading.pm (loaded by overload)
    #   4   1495     3.566ms( 26%)    warnings.pm (loaded by subs)
    #   7     45     0.174ms(  1%)    warnings/register.pm (loaded by vars)
    # End of stats
    9

I'm also not seeing Proc::ProcessTable as a dependency for Data::Dump::Color, so currently not sure who loads it.

    $ lcpan deps Data::Dump::Color --rel ALL -R
    +------------------------------------------+-----------+-----------+---------+-----------------------+-----------------------------+------------+
    | module                                   | author    |   version | is_core | dist                  | module_dist                 | rel        |
    +------------------------------------------+-----------+-----------+---------+-----------------------+-----------------------------+------------+
    | ColorThemeBase::Static::FromStructColors | PERLANCAR |     0.006 |       0 |                       | ColorThemeBase-Static       | requires   |
    |   Color::RGB::Util                       | PERLANCAR |     0.600 |       0 | ColorThemeBase-Static | Color-RGB-Util              | requires   |
    |     Digest::SHA                          | MSHELOR   |         0 |       1 | Color-RGB-Util        | Digest-SHA                  | requires   |
    | ColorThemeUtil::ANSI                     | PERLANCAR |         0 |       0 |                       | ColorThemeUtil-ANSI         | requires   |
    |   Color::ANSI::Util                      | PERLANCAR |     0.164 |       0 | ColorThemeUtil-ANSI   | Color-ANSI-Util             | requires   |
    | Data::Dump::FilterContext                | GARU      |         0 |       0 |                       | Data-Dump                   | requires   |
    | Data::Dump::Filtered                     | GARU      |         0 |       0 |                       | Data-Dump                   | requires   |
    | Exporter                                 | TODDR     |      5.57 |       1 |                       | Exporter                    | requires   |
    |   Carp                                   | XSAWYERX  |      1.05 |       1 | Exporter              | Carp                        | requires   |
    |     Test::More                           | EXODIST   |      0.47 |       1 | Carp                  | Test-Simple                 | requires   |
    |       File::Temp                         | ETHER     |         0 |       1 | Test-Simple           | File-Temp                   | requires   |
    |         constant                         | RJBS      |         0 |       1 | File-Temp             | constant                    | requires   |
    |         IO::Seekable                     | TODDR     |         0 |       1 | File-Temp             | IO                          | requires   |
    |         IO::Handle                       | TODDR     |         0 |       1 | File-Temp             | IO                          | requires   |
    |         File::Path                       | JKEENAN   |      2.06 |       1 | File-Temp             | File-Path                   | requires   |
    |       Module::Pluggable                  | SIMONW    |         0 |       0 | Test-Simple           | Module-Pluggable            | suggests   |
    |         Module::Runtime                  | ZEFRAM    |     0.012 |       0 | Module-Pluggable      | Module-Runtime              | recommends |
    |       Storable                           | NWCLARK   |         0 |       1 | Test-Simple           | Storable                    | requires   |
    |     IPC::Open3                           | PEVANS    |    1.0103 |       1 | Carp                  | Amiga-ARexx                 | requires   |
    |     ExtUtils::MakeMaker                  | BINGOS    |         0 |       1 | Carp                  | ExtUtils-MakeMaker          | requires   |
    |       Data::Dumper                       | NWCLARK   |         0 |       1 | ExtUtils-MakeMaker    | Data-Dumper                 | requires   |
    |       Encode                             | DANKOGAI  |         0 |       1 | ExtUtils-MakeMaker    | Encode                      | requires   |
    |       File::Spec                         | XSAWYERX  |       0.8 |       1 | ExtUtils-MakeMaker    | PathTools                   | requires   |
    |       Pod::Man                           | RRA       |         0 |       1 | ExtUtils-MakeMaker    | podlators                   | requires   |
    |     Config                               |           |         0 |       1 | Carp                  |                             | requires   |
    |   Test::Pod                              | ETHER     |      1.18 |       0 | Exporter              | Test-Pod                    | recommends |
    |     Test::Builder::Tester                | EXODIST   |      1.02 |       1 | Test-Pod              | Test-Simple                 | requires   |
    |     Pod::Simple                          | KHW       |      3.05 |       1 | Test-Pod              | Pod-Simple                  | requires   |
    |       Cwd                                | XSAWYERX  |         0 |       1 | Pod-Simple            | PathTools                   | requires   |
    |       Pod::Escapes                       | NEILB     |      1.04 |       1 | Pod-Simple            | Pod-Escapes                 | requires   |
    |       Text::Wrap                         | ARISTOTLE | 98.112902 |       1 | Pod-Simple            | Text-Tabs+Wrap              | requires   |
    |       if                                 | XSAWYERX  |         0 |       1 | Pod-Simple            | if                          | requires   |
    |     File::Find                           | RJBS      |         0 |       1 | Test-Pod              | Amiga-ARexx                 | requires   |
    |   Test::Pod::Coverage                    | NEILB     |      1.04 |       0 | Exporter              | Test-Pod-Coverage           | recommends |
    |     Test::Builder                        | EXODIST   |         0 |       1 | Test-Pod-Coverage     | Test-Simple                 | requires   |
    |     Pod::Coverage                        | RCLAMP    |         0 |       0 | Test-Pod-Coverage     | Pod-Coverage                | requires   |
    |       Devel::Symdump                     | ANDK      |      2.01 |       0 | Pod-Coverage          | Devel-Symdump               | requires   |
    |         Compress::Zlib                   | PMQS      |         0 |       1 | Devel-Symdump         | IO-Compress                 | requires   |
    |           Compress::Raw::Bzip2           | PMQS      |     2.206 |       1 | IO-Compress           | Compress-Raw-Bzip2          | requires   |
    |           Compress::Raw::Zlib            | PMQS      |     2.206 |       1 | IO-Compress           | Compress-Raw-Zlib           | requires   |
    |           Time::Local                    | DROLSKY   |         0 |       1 | IO-Compress           | Time-Local                  | requires   |
    |       Pod::Find                          | MAREKR    |      0.21 |       0 | Pod-Coverage          | Pod-Parser                  | requires   |
    |       Pod::Parser                        | MAREKR    |      1.13 |       0 | Pod-Coverage          | Pod-Parser                  | requires   |
    | MIME::Base64                             | CAPOEIRAB |         0 |       1 |                       | MIME-Base64                 | requires   |
    |   XSLoader                               | SAPER     |         0 |       1 | MIME-Base64           | XSLoader                    | requires   |
    | Module::Load::Util                       | PERLANCAR |     0.004 |       0 |                       | Module-Load-Util            | requires   |
    |   Regexp::Pattern::Perl::Module          | PERLANCAR |     0.005 |       0 | Module-Load-Util      | Regexp-Pattern-Perl         | requires   |
    | Scalar::Util                             | PEVANS    |         0 |       1 |                       | Scalar-List-Utils           | requires   |
    | Scalar::Util::LooksLikeNumber            | PERLANCAR |         0 |       0 |                       | Scalar-Util-LooksLikeNumber | recommends |
    | Term::ANSIColor                          | RRA       |         0 |       1 |                       | Term-ANSIColor              | requires   |
    | overload                                 | PEVANS    |         0 |       1 |                       | AnyDBM_File                 | requires   |
    | parent                                   | CORION    |         0 |       1 |                       | parent                      | requires   |
    | perl                                     |           |  5.010001 |       1 |                       |                             | requires   |
    | strict                                   | PEVANS    |         0 |       1 |                       | AnyDBM_File                 | requires   |
    | subs                                     | PEVANS    |         0 |       1 |                       | AnyDBM_File                 | requires   |
    | vars                                     | PEVANS    |         0 |       1 |                       | AnyDBM_File                 | requires   |
    | warnings                                 | PEVANS    |         0 |       1 |                       | AnyDBM_File                 | requires   |
    +------------------------------------------+-----------+-----------+---------+-----------------------+-----------------------------+------------+

**Comment by perlancar** [comment]
UPDATE: sorry, I just read that it's File::Find which uses Proc::ProcessTable. So the next step is to trace how File::Find gets called, because the distribution metadata only lists File::Find as a test dependency (via Test::Pod).

**Comment by scottchiefbaker** [comment]
How do we track how `File::Find` gets called? I was thinking maybe it had something to do with loading the color scheme? I can recreate the problem pretty easily on a clean RedHat box.

**Comment by perlancar** [comment]
You can use `Devel::EndStats` like above, which will tellsyou which module loads `File::Find`. Or, as suggested in one of the comments on your Reddit post, add a `warn()` (with `-d:Confess` perl flag) or call `Carp'`s `confess()` in `Proc::ProcessTable` to get a full stack trace.

**Comment by scottchiefbaker** [comment]
I ran a quick test of the issue through NYTProf and this is what it came up with. That is quite the tree to get the `Proc::ProcessTable`

[nytprof.tar.gz](https://github.com/perlancar/perl-Data-Dump-Color/files/14055898/nytprof.tar.gz)

**Comment by perlancar** [comment]
Ah okay, so it looks like the culprit is [Term::Detect::Software](https://metacpan.org/pod/Term::Detect::Software), which employs a bunch of heuristics to guess the terminal software. Try to look at the source code of that module. My terminal is Konsole, which can be guessed cheaply. What terminal are you using? I'm guessing it's one below line 133, e.g. one of the Gnome ones, or rxvt, mrxvt, st, pterm, or xvt.

I could add a flag to let user avoid doing guessing using Proc::Find::Parents (and Proc::ProcessTable), or find a cheaper way to detect one of the abovementioned terminals.

**Comment by scottchiefbaker** [comment]
I bet you're right! It's probably calling `Proc::Find::Parents`! 

I'm running the Windows Subsystem for Linux and using a "Debian" terminal to SSH. When I check the `$TERM` I see: `xterm-256color`. I didn't think about testing in a different terminal. I suspect we just need to update `Term::Detect::Software` since WSL is pretty popular now, and things will be fast again.

**Comment by perlancar** [comment]
My laptop is not powerful enough to run a virtualized Win10/Win11 to test WSL. You are welcome to add a detection heuristic to `Term::Detect::Software`. But in the meantime, I've added `PERL_TERM_DETECT_SOFTWARE_ENGINE` support to it. You can set that environment variable to something like `xterm` to get 256 color support while avoiding the expensive detection routine.

**Comment by scottchiefbaker** [comment]
There is a pull request pending on `Term::Detect::Software` which should solve the problem.

**Comment by scottchiefbaker** [comment]
FWIW I wrote a [Perl Git prompt](https://github.com/scottchiefbaker/perl-git-prompt) tool in 2013 with the note:

> This script assumes you have 256 color terminal support. It's 2013, you should have a 256 color terminal. If you still have a 16 color terminal no guarantees how this will look.

and I have received **zero** complaints. I think 99% of terminals people use today are at **least** 256 color capable. Maybe for `Data::Dump::Color` we drop the terminal check all together and just default to 256 colors? We can add a runtime option to force 16 colors if the user wants to override. 

This would simplify things and also remove a fair amount of dependencies from `Data::Dump::Color` as well.

**Comment by perlancar** [comment]
Agreed, defaulting to 256 color is sensible. I think the only notable exception is Linux virtual console (or equivalents in other OS) which works in actual text mode (not under X/Wayland) and is 8/16 color only (without fbterm). I don't think many people work in that environment, but we just need to provide a graceful fallback to 8/16 color.

**Comment by scottchiefbaker** [comment]
I think that's a good strategy going forward. Do you need anything from me to work towards defaulting to 256 color mode?

**Comment by perlancar** [comment]
Instead of creating yet another module, I decided to modify `Term::Detect::Software` to disable checking via process names by default (to enable it, one must set an environment variable), and to downgrade the dependency `Proc::Find::Parents` to runtime recommends instead of runtime requires.

**Comment by scottchiefbaker** [comment]
Is that new change on CPAN? If I update `Term::Detect::Software` with `cpanm` will I be able to test?

**Comment by perlancar** [comment]
Yes, I've pushed it to CPAN a couple of days ago, 0.227.

**Comment by scottchiefbaker** [comment]
OK I just did some preliminary testing and things look good so far.
