### ISSUE TITLE
Weird output when mapping true/false?

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#5]
I have the following JSON that I'm reading in to a hash with JSON::PP

```
{"result":{"login":true,"delete":true,"provision":true},"id":1}
```

If I print it out with `Data::Dumper` I get this (not ideal, but understandable) output:

```
$VAR1 = {
          'provision' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
          'delete' => $VAR1->{'provision'},
          'login' => $VAR1->{'provision'}
        };
```

If I print it with `dd` I get:

```
do {
  my $a = {
    delete    => bless(do{\(my $o = 1)}, "JSON::PP::Boolean"), # {0}
    login     => 'fix',                                        # {1}
    provision => 'fix',                                        # {2}
  };
  $a{login} = ${$a{delete}};
  $a{provision} = ${$a{delete}};
  $a;
}
```

`login` and `provision` are definitely NOT correct. Any ideas?

**Comment by scottchiefbaker** [comment]
Simple way to recreate/test this problem:

```
use strict;
use warnings;
use Data::Dump::Color;
use Data::Dumper;
use JSON::PP;

my $json = '{"result":{"login":true,"delete":true,"provision":true},"id":1}';
my $x    = decode_json($json);

print Dumper($x);
dd($x);
```

**Comment by perlancar** [comment]
The above is actually correct. The JSON module decodes JSON's true/false into singleton objects (scalarrefs), not Perl scalar 1/''. Since they are singleton, when dumping multiple occurrences like in the above case of 'delete', 'login', 'provision' pair values they all refer to the same object and must be dumped using 'fix'-es technique. The Data::Dumper version on the other hand will not produce the correct thing.

If you want JSON booleans to become normal 1/'', you can use Data::Clean::FromJSON first, e.g.:


    use warnings;                                                                                                                                                                             

    use Data::Clean::FromJSON;                                                                                                                                                                

    use Data::Dump::Color;                                                                                                                                                                    

    use Data::Dumper;                                                                                                                                                                         

    use JSON::PP;                                                                                                                                                                             
                                                                                                                                                                                          

    my $json = '{"result":{"login":true,"delete":true,"provision":true},"id":1}';                                                                                                             

    my $x    = decode_json($json);                                                                                                                                                            
                                                                                                                                                                                          

    my $cleanser = Data::Clean::FromJSON->get_cleanser;                                                                                                                                       
                                                                                                                                                                                          

    print Dumper($cleanser->clone_and_clean($x));                                                                                                                                             
    dd($cleanser->clone_and_clean($x));

**Comment by perlancar** [comment]
IIRC the JSON modules can also be configured to decode JSON's true/false into normal Perl scalars, but looking at the JSON::PP code just now the configuration doesn't seem to be there. Maybe I remember incorrectly.

**Comment by scottchiefbaker** [comment]
What is the "fix" syntax? I'm not familiar with that, it threw me off.

**Comment by perlancar** [comment]
If you have two or more of the same references (meaning it refers to the same data) mentioned in the same data structure, you will see this:

    % perl -MData::Dump -E'$href = {}; dd [$href, $href]'
    do {
      my $a = [{}, 'fix'];
      $a->[1] = $a->[0];
      $a;
    }

If you dump it as:

    [{}, {}]

it will be incorrect because it will create two different hashrefs. That's why a hack with do {} block and multiple statements/assignments is needed to recreate the same structure. Compare:

    % perl -MData::Dump -E'$href = {}; $data = [$href, $href]; $data->[0]{foo} = "bar"; dd $data->[1]'
    { foo => "bar" }

vs:

    % perl -MData::Dump -E'$data = [{}, {}]; $data->[0]{foo} = "bar"; dd $data->[1]'
    {}

In the first case, if you modify the hash at `$data->[0]`, you will also see the change in `$data->[1]` because the hash is the same. But in the second case, you have two different hashes.

**Comment by jonassmedegaard** [comment]
Data::Printer provides an (at least to me) more intuitive output in such cases:

```perl
perl -MDDP -E'$href = {}; p [$href, $href]->@*'
[
    [0] {},
    [1] var[0]
]
```

**Comment by perlancar** [comment]
Yup, in general I agree the 'fix' should be replaced with a reference to an item, e.g. 'var[0]'. This should ideally be done in Data::Dump though, and we'll adopt it. Any taker? :)

**Comment by jonassmedegaard** [comment]
Uhm, how about deprecating Data::Dump::Color and use Data::Printer instead?
I find [this](https://metacpan.org/pod/Data::Printer#DESCRIPTION) enlightening:
> The ever-popular Data::Dumper is a fantastic tool, meant to stringify data structures in a way they are suitable for being "eval"'ed back in. The thing is, a lot of people keep using it (and similar ones, like Data::Dump) to print data structures and objects on screen for inspection and debugging, and while you can use those modules for that, it doesn't mean you should.

**Comment by jonassmedegaard** [comment]
It seems that all reverse dependencies of Data::Dump::Color on CPAN was authored by you, @perlancar so should not need any coordination to move to Data::Printer - which has fewer dependencies and supporting it does not even need a dependency (can be lowered to a recommendation or suggestion) depending on how it is used.

**Comment by perlancar** [comment]
Well, I personally happen to like Data::Dump (and Data::Dump::Color) output, because it's pure Perl syntax. I know there's at least one user @scottchiefbaker which uses it too, although he doesn't publish module that requires it.

**Comment by perlancar** [comment]
> It seems that all reverse dependencies of Data::Dump::Color on CPAN was authored by you, @perlancar so should not need any coordination to move to Data::Printer - which has fewer dependencies and supporting it does not even need a dependency (can be lowered to a recommendation or suggestion) depending on how it is used.

Even if I wanted to move to Data::Printer, not all cases would be appropriate. For example, in App-SerializeUtils where I have CLIs like json2dd, dd2json, etc, I'm using Data::Dump::Color as a proper Perl dumper and the eval-ability is useful here.

**Comment by scottchiefbaker** [comment]
I use `Data::Dump::Color` exclusively for all my debug print needs. In fact @leonerd and I were discussing on IRC that we'd like to see a better debug print in future versions of Perl. `Data::Dumper` is pretty antiquated in 2021.

The biggest drawback I see of **all** the current debug printers is that they try TOO hard to make the output Perl syntax. That's nice and all but it doesn't necessarily make the best human-readable output. One of the best things about `Data::Dump::Color` is that it prints things in mostly human readable format. I want my debug print to be 100% human readable.

This bug is a good example of something that should be better tuned for human consumption, not machines. I don't really care what Perl does internally to track variables and link them, I care how I read/interpret the output. Because 99 times out of a 100, me (as a human) is reading the output, not the Perl interpreter.

**Comment by perlancar** [comment]
> Yup, in general I agree the 'fix' should be replaced with a reference to an item, e.g. 'var[0]'. This should ideally be done in Data::Dump though, and we'll adopt it. Any taker? :)

Ok, I went ahead and committed b1e3ba8.

    # before
    % perl -MData::Dump::Color -E'$var=[0,1,[],3]; $var->[1]=$var->[2]; dd $var'
    do {
      my $a = [0, [], 'fix', 3];
      $a[2] = $a[1];
      $a;
    }

    # after
    do {
      my $var = [0, [], '$var->[1]', 3];
      $var->[2] = $var->[1];
      $var;
    }
