### ISSUE TITLE
"Negative repeat count does nothing" has resurfaced

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#7]
It appears that #4 has recurred in the latest version of `Data::Dump::Color`. Checking the [actual code](https://github.com/perlancar/perl-Data-Dump-Color/blob/master/lib/Data/Dump/Color.pm#L525) it looks like the fix from #6 has been reverted?

We just need to be 100% sure that the repeat count is positive.

**Comment by perlancar** [comment]
You mean commit 26dcb29? I think it's still there. I haven't done much to the codebase recently.

**Comment by scottchiefbaker** [comment]
If you look at the code on line 525 it's redundant. I don't know how I missed this back when it was committed. I think simply removing line 525 will do the trick.

**Comment by perlancar** [comment]
> If you look at the code on line 525 it's redundant. I don't know how I missed this back when it was committed. I think simply removing line 525 will do the trick.

I tried your test data in #4 (commit 1ffcf56), but it fails to produce the warnings. With or without removing line 525. With perl 5.24.0 and 5.24.1.

But I removed line 525 anyway (commit 0f86459).

Could you try to reproduce the warning, using the test data?

**Comment by scottchiefbaker** [comment]
I haven't seen this issue in a while. I'll close this and let you know if it crops up again.

Thanks for the fix. Sorry for the delay :)
