### ISSUE TITLE
Would it be possible to make Data::Dump::Color fatpackable?

### ISSUE THREAD

**Issue by scottchiefbaker** [perlancar/perl-Data-Dump-Color#8]
I love `Data::Dump::Color`, I use it every day. It would be great if it were pure Perl and thus fatpackable. What is the feasibility of doing this?

I **think** the only requirement is `lookslikeanumber` which should be pretty easy to implement in Pure Perl.

Maybe I'm way off?

**Comment by perlancar** [comment]
Scalar::Util::LooksLikeNumber's looks_like_number(), or the old version of Scalar::Util's looks_like_number(), which returns numeric value to indicate the numeric detail of a scalar, is not implementable in pure Perl. Pure Perl or the new Scalar::Util's looks_like_number() cannot distinguish between these two cases:

    $var = "123";
    $var = 123;

I've committed a change to use the new Scalar::Util's looks_like_number() but I'm considering whether I'm willing to forgo this capability.

**Comment by perlancar** [comment]
BTW, you're correct that Scalar::Util::LooksLikeNumber is the only non-core XS prereq. I like fatpackability. So maybe I can make this prereq optional.

**Comment by perlancar** [comment]
> BTW, you're correct that Scalar::Util::LooksLikeNumber is the only non-core XS prereq. I like fatpackability. So maybe I can make this prereq optional.

0.243 has been released which does this.

**Comment by scottchiefbaker** [comment]
What if you were to use the same logic that `JSON::PP` does?

https://metacpan.org/release/JSON-PP/source/lib/JSON/PP.pm#L460-467

That seems pretty portable.

**Comment by scottchiefbaker** [comment]
Doing some quick tests it seems accurate enough for debug print:

```
use JSON::PP;
say JSON::PP::_looks_like_number(4)     ? 'yes' : 'no'; # yes
say JSON::PP::_looks_like_number(0)     ? 'yes' : 'no'; # yes
say JSON::PP::_looks_like_number(undef) ? 'yes' : 'no'; # no
say JSON::PP::_looks_like_number("foo") ? 'yes' : 'no'; # no 
say JSON::PP::_looks_like_number([1,2]) ? 'yes' : 'no'; # no
```

**Comment by perlancar** [comment]
> What if you were to use the same logic that `JSON::PP` does?
> 
> https://metacpan.org/release/JSON-PP/source/lib/JSON/PP.pm#L460-467
> 
> That seems pretty portable.

Interesting, will take a look. This part could perhaps be refactored to a separate module. As I need this logic also in a few other modules.

**Comment by perlancar** [comment]
> say JSON::PP::_looks_like_number(4)     ? 'yes' : 'no'; # yes

This is the important part:

    % perl -MJSON::PP -E'say JSON::PP::_looks_like_number(4)'
    1
    % perl -MJSON::PP -E'say JSON::PP::_looks_like_number("4")'
    
looks good.

**Comment by perlancar** [comment]
> I love `Data::Dump::Color`, I use it every day. It would be great if it were pure Perl and thus fatpackable. What is the feasibility of doing this?
> 
> I **think** the only requirement is `lookslikeanumber` which should be pretty easy to implement in Pure Perl.
> 
> Maybe I'm way off?

Btw, do you create lots of fatpack scripts? Have you tried datapacking too? [1] I also created depak [2] which can create fatpacked/datapacked scripts (including packing recursive deps) in a single step.

[1] https://metacpan.org/pod/Module::DataPack
[2] https://metacpan.org/pod/depak

**Comment by scottchiefbaker** [comment]
I haven't even heard of DataPack... I will check it out.

`JSON::PP` being core makes relying on this (no real dependencies) a lot easier.

**Comment by perlancar** [comment]
Since Scalar::Util::LooksLikeNumber has now been made optional, I'm gonna close this now. I am interested in replacing Scalar::Util::LooksLikeNumber with JSON::PP will revisit this in the future.
